// <auto-generated />
using System;
using FlowCare.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowCare.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317173405_db function for rescheduling appointment")]
    partial class dbfunctionforreschedulingappointment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BranchSlotPosition", b =>
                {
                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<long?>("RankPosition")
                        .HasColumnType("bigint");

                    b.Property<string>("Service")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.ActionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("action_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "SEED_IMPORT"
                        },
                        new
                        {
                            Id = 2,
                            Type = "APPOINTMENT_BOOKED"
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttachementReference")
                        .HasColumnType("text");

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("SlotId");

                    b.HasIndex("StaffId");

                    b.HasIndex("BranchId", "ServiceTypeId", "CreatedAt");

                    b.ToTable("appointments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 15, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            CustomerId = 1,
                            ServiceTypeId = 1,
                            SlotId = 1,
                            StaffId = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 15, 10, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            CustomerId = 2,
                            ServiceTypeId = 6,
                            SlotId = 9,
                            StaffId = 7,
                            Status = 1
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionTypeId")
                        .HasColumnType("integer");

                    b.Property<int?>("ActionTypeId1")
                        .HasColumnType("integer");

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityId")
                        .HasColumnType("integer");

                    b.Property<int>("EntityTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActionTypeId");

                    b.HasIndex("ActionTypeId1");

                    b.HasIndex("EntityTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("audit_logs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionTypeId = 1,
                            ActorId = 1,
                            EntityId = 1,
                            EntityTypeId = 1,
                            MetadataJson = "{\"note\":\"Initial seed import executed\"}",
                            RoleId = 1,
                            Timestamp = new DateTimeOffset(new DateTime(2026, 2, 15, 10, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            ActionTypeId = 2,
                            ActorId = 1,
                            EntityId = 1,
                            EntityTypeId = 2,
                            MetadataJson = "{\"slot_id\":1,\"branch_id\":1,\"service_type_id\":1}",
                            RoleId = 4,
                            Timestamp = new DateTimeOffset(new DateTime(2026, 2, 15, 10, 12, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RetentionPerioud")
                        .HasColumnType("integer");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Al Khuwair, Muscat",
                            City = "Muscat",
                            IsActive = true,
                            Name = "FlowCare Muscat - Al Khuwair",
                            RetentionPerioud = 30,
                            Timezone = "Asia/Muscat"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Al Humbar, Suhar",
                            City = "Suhar",
                            IsActive = true,
                            Name = "FlowCare Suhar - Al Humbar",
                            RetentionPerioud = 30,
                            Timezone = "Asia/Muscat"
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.BranchWorkingHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BranchId")
                        .HasMaxLength(64)
                        .HasColumnType("integer");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("branch_working_hours", (string)null);
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IdRefImage")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed.h@example.com",
                            FullName = "Ahmed Al Harthy",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEOfn1uX/3oUCt3hcVLPLFdCP1Zd5XjUKIvXGYq3hRoQZmXXUn+XZpLFCfkECprifyQ==",
                            Phone = "+96890000001",
                            Username = "cust_ahmed"
                        },
                        new
                        {
                            Id = 2,
                            Email = "fatima.z@example.com",
                            FullName = "Fatima Al Zadjali",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEB3n4s8ogXr0nisk5WHlpMdKlfqqcfyKb9wAXP6Qlicv3rISUagNTgTcpJccKZ/3BA==",
                            Phone = "+96890000002",
                            Username = "cust_fatima"
                        },
                        new
                        {
                            Id = 3,
                            Email = "khalid.a@example.com",
                            FullName = "Khalid Al Amri",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEI25+4Cf8C8Gnasac1q2lNeX6Xj7kYUU3Ey2brxZyS/Ox07YDMxBMwsQBoUwYavfJA==",
                            Phone = "+96890000003",
                            Username = "cust_khalid"
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("entity_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "SYSTEM"
                        },
                        new
                        {
                            Id = 2,
                            Type = "APPOINTMENT"
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Title = "BranchManager"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Staff"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Customer"
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.ServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("service_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Description = "Account questions, basic requests, ticket follow-ups",
                            DurationMinutes = 15,
                            IsActive = true,
                            Name = "Customer Support"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Description = "Check documents, validate requirements, approvals",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "Document Verification"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Description = "Priority desk for special cases",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "VIP Service Desk"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 2,
                            Description = "Account questions, basic requests, ticket follow-ups",
                            DurationMinutes = 15,
                            IsActive = true,
                            Name = "Customer Support"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 2,
                            Description = "New customer onboarding and profile creation",
                            DurationMinutes = 20,
                            IsActive = true,
                            Name = "New Registration"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Description = "Escalations handling and complaints resolution",
                            DurationMinutes = 25,
                            IsActive = true,
                            Name = "Complaints & Escalations"
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("StaffId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("StaffId");

                    b.HasIndex("BranchId", "ServiceTypeId", "StaffId", "StartAt");

                    b.ToTable("slots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 1,
                            StaffId = 4,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 1,
                            StaffId = 4,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 17, 10, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 2,
                            StaffId = 4,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 1,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 18, 11, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 3,
                            StaffId = 5,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 18, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 19, 12, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 2,
                            StaffId = 4,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 19, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 1,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 3,
                            StaffId = 5,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 20, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 2,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 4,
                            StaffId = 6,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 2,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 50, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 5,
                            StaffId = 6,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 16, 9, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 9,
                            BranchId = 2,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 17, 10, 25, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 6,
                            StaffId = 7,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 17, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 10,
                            BranchId = 2,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 18, 10, 55, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 6,
                            StaffId = 7,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 18, 10, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 11,
                            BranchId = 2,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 19, 11, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 4,
                            StaffId = 6,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 19, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 12,
                            BranchId = 2,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 20, 12, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 5,
                            StaffId = 6,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 20, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 13,
                            BranchId = 1,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 21, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 1,
                            StaffId = 4,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 21, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        },
                        new
                        {
                            Id = 14,
                            BranchId = 2,
                            Capacity = 1,
                            EndAt = new DateTimeOffset(new DateTime(2026, 2, 22, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0)),
                            IsActive = true,
                            ServiceTypeId = 4,
                            StaffId = 6,
                            StartAt = new DateTimeOffset(new DateTime(2026, 2, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 4, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("RoleId");

                    b.ToTable("staff", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Email = "admin@flowcare.local",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEC8xDeNpz9E8nc11DDSd4dcD9PVwadnRFJxfk8nfk7FqLUiuopHjmBJ44hGdz954jQ==",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Email = "aisha.b@flowcare.local",
                            FullName = "Aisha Al Balushi",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEICab8+wTwJozhRWUwreIBIMBkh3s2MHVKM1Yzp69eLAmZyvBMmtsK5ZSg9b+9NGJw==",
                            RoleId = 2,
                            Username = "mgr_muscat"
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 2,
                            Email = "hamad.h@flowcare.local",
                            FullName = "Hamad Al Hinai",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEES+cw79Pa3WRk3nd1PVkOcv7ZVXJ5KJGfuSi4QNncMFCxFXTyUynYUAvukbqtsmkQ==",
                            RoleId = 2,
                            Username = "mgr_suhar"
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 1,
                            Email = "salim.r@flowcare.local",
                            FullName = "Salim Al Rashdi",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEEzqb3dbU8+IioqpTJ0sycCRu3H90O6n7sG3DZYMc2woBJy+ycq94hESNK4mb0YAsg==",
                            RoleId = 3,
                            Username = "staff_muscat_1"
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            Email = "maha.s@flowcare.local",
                            FullName = "Maha Al Shukaili",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEIHjdTv2h1anEJbgnEH/C408rfryyQWwwWpYzEz0pxy+bjhrKjj+Zk3FRm5rEV8pOw==",
                            RoleId = 3,
                            Username = "staff_muscat_2"
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 2,
                            Email = "nasser.m@flowcare.local",
                            FullName = "Nasser Al Maqbali",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEBOMdOXpbpPdJwdkQSW7KnPbBtwDrXTZ6zSCmD2p9VwsSHVG9xZcIDOaEJWLqs4L0w==",
                            RoleId = 3,
                            Username = "staff_suhar_1"
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 2,
                            Email = "reem.k@flowcare.local",
                            FullName = "Reem Al Kindi",
                            IsActive = true,
                            PasswordHash = "AQAAAAIAAYagAAAAEEfgZzmxWk+UqM6tXA+gt+wXwIuYwLSRO1EAbldfe1nZuwFVYVKBIQlkZD9AedT00w==",
                            RoleId = 3,
                            Username = "staff_suhar_2"
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.StaffServiceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceTypeId")
                        .HasMaxLength(64)
                        .HasColumnType("integer");

                    b.Property<int>("StaffId")
                        .HasMaxLength(64)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("StaffId", "ServiceTypeId")
                        .IsUnique();

                    b.ToTable("staff_service_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ServiceTypeId = 1,
                            StaffId = 4
                        },
                        new
                        {
                            Id = 2,
                            ServiceTypeId = 2,
                            StaffId = 4
                        },
                        new
                        {
                            Id = 3,
                            ServiceTypeId = 3,
                            StaffId = 5
                        },
                        new
                        {
                            Id = 4,
                            ServiceTypeId = 4,
                            StaffId = 6
                        },
                        new
                        {
                            Id = 5,
                            ServiceTypeId = 5,
                            StaffId = 6
                        },
                        new
                        {
                            Id = 6,
                            ServiceTypeId = 6,
                            StaffId = 7
                        });
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.StaffWorkingHour", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("StaffId")
                        .HasMaxLength(64)
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "DayOfWeek");

                    b.ToTable("staff_working_hours", (string)null);
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.Customer", "Customer")
                        .WithMany("Appointments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.Slot", "Slot")
                        .WithMany("Appointments")
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("ServiceType");

                    b.Navigation("Slot");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.ActionType", "ActionType")
                        .WithMany()
                        .HasForeignKey("ActionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.ActionType", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActionTypeId1");

                    b.HasOne("FlowCare.Domain.Entities.EntityType", "EntityType")
                        .WithMany("AuditLogs")
                        .HasForeignKey("EntityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionType");

                    b.Navigation("EntityType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.BranchWorkingHour", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.Branch", "Branch")
                        .WithMany("WorkingHours")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.ServiceType", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.Branch", "Branch")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Slot", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.Branch", "Branch")
                        .WithMany("Slots")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("Slots")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.Staff", "Staff")
                        .WithMany("Slots")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("ServiceType");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Staff", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.StaffServiceType", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.ServiceType", "ServiceType")
                        .WithMany("Staff")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowCare.Domain.Entities.Staff", "Staff")
                        .WithMany("ServiceTypes")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceType");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.StaffWorkingHour", b =>
                {
                    b.HasOne("FlowCare.Domain.Entities.Staff", "Staff")
                        .WithMany("WorkingHours")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.ActionType", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Branch", b =>
                {
                    b.Navigation("ServiceTypes");

                    b.Navigation("Slots");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.EntityType", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.ServiceType", b =>
                {
                    b.Navigation("Slots");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Slot", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("FlowCare.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("ServiceTypes");

                    b.Navigation("Slots");

                    b.Navigation("WorkingHours");
                });
#pragma warning restore 612, 618
        }
    }
}
